package modelo.dto;
// Generated 04-sep-2018 14:31:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private Integer idEquipo;
     private Liga liga;
     private Usuario usuario;
     private String nombreEquipo;
     private String logoEquipo;
     private Set<Jugador> jugadors = new HashSet<Jugador>(0);
     private Set<Partido> partidosForEquipo2 = new HashSet<Partido>(0);
     private Set<Partido> partidosForEquipo1 = new HashSet<Partido>(0);
     private Set<Premio> premios = new HashSet<Premio>(0);

    public Equipo() {
    }

	
    public Equipo(Liga liga, Usuario usuario, String nombreEquipo, String logoEquipo) {
        this.liga = liga;
        this.usuario = usuario;
        this.nombreEquipo = nombreEquipo;
        this.logoEquipo = logoEquipo;
    }
    public Equipo(Liga liga, Usuario usuario, String nombreEquipo, String logoEquipo, Set<Jugador> jugadors, Set<Partido> partidosForEquipo2, Set<Partido> partidosForEquipo1, Set<Premio> premios) {
       this.liga = liga;
       this.usuario = usuario;
       this.nombreEquipo = nombreEquipo;
       this.logoEquipo = logoEquipo;
       this.jugadors = jugadors;
       this.partidosForEquipo2 = partidosForEquipo2;
       this.partidosForEquipo1 = partidosForEquipo1;
       this.premios = premios;
    }
   
    public Integer getIdEquipo() {
        return this.idEquipo;
    }
    
    public void setIdEquipo(Integer idEquipo) {
        this.idEquipo = idEquipo;
    }
    public Liga getLiga() {
        return this.liga;
    }
    
    public void setLiga(Liga liga) {
        this.liga = liga;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombreEquipo() {
        return this.nombreEquipo;
    }
    
    public void setNombreEquipo(String nombreEquipo) {
        this.nombreEquipo = nombreEquipo;
    }
    public String getLogoEquipo() {
        return this.logoEquipo;
    }
    
    public void setLogoEquipo(String logoEquipo) {
        this.logoEquipo = logoEquipo;
    }
    public Set<Jugador> getJugadors() {
        return this.jugadors;
    }
    
    public void setJugadors(Set<Jugador> jugadors) {
        this.jugadors = jugadors;
    }
    public Set<Partido> getPartidosForEquipo2() {
        return this.partidosForEquipo2;
    }
    
    public void setPartidosForEquipo2(Set<Partido> partidosForEquipo2) {
        this.partidosForEquipo2 = partidosForEquipo2;
    }
    public Set<Partido> getPartidosForEquipo1() {
        return this.partidosForEquipo1;
    }
    
    public void setPartidosForEquipo1(Set<Partido> partidosForEquipo1) {
        this.partidosForEquipo1 = partidosForEquipo1;
    }
    public Set<Premio> getPremios() {
        return this.premios;
    }
    
    public void setPremios(Set<Premio> premios) {
        this.premios = premios;
    }




}


