package modelo.dto;
// Generated 04-sep-2018 14:31:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoUsuario generated by hbm2java
 */
public class EstadoUsuario  implements java.io.Serializable {


     private Integer idEstadoUsuario;
     private String descripcionEstadoUsuario;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public EstadoUsuario() {
    }

	
    public EstadoUsuario(String descripcionEstadoUsuario) {
        this.descripcionEstadoUsuario = descripcionEstadoUsuario;
    }
    public EstadoUsuario(String descripcionEstadoUsuario, Set<Usuario> usuarios) {
       this.descripcionEstadoUsuario = descripcionEstadoUsuario;
       this.usuarios = usuarios;
    }

    public EstadoUsuario(Integer idEstadoUsuario) {
        this.idEstadoUsuario = idEstadoUsuario;
    }
    
    

    
   
    public Integer getIdEstadoUsuario() {
        return this.idEstadoUsuario;
    }
    
    public void setIdEstadoUsuario(Integer idEstadoUsuario) {
        this.idEstadoUsuario = idEstadoUsuario;
    }
    public String getDescripcionEstadoUsuario() {
        return this.descripcionEstadoUsuario;
    }
    
    public void setDescripcionEstadoUsuario(String descripcionEstadoUsuario) {
        this.descripcionEstadoUsuario = descripcionEstadoUsuario;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


