package modelo.dto;
// Generated 04-sep-2018 14:31:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Liga generated by hbm2java
 */
public class Liga  implements java.io.Serializable {


     private Integer idLiga;
     private String descripcionLiga;
     private Set<Equipo> equipos = new HashSet<Equipo>(0);

    public Liga() {
    }

	
    public Liga(String descripcionLiga) {
        this.descripcionLiga = descripcionLiga;
    }
    public Liga(String descripcionLiga, Set<Equipo> equipos) {
       this.descripcionLiga = descripcionLiga;
       this.equipos = equipos;
    }
   
    public Integer getIdLiga() {
        return this.idLiga;
    }
    
    public void setIdLiga(Integer idLiga) {
        this.idLiga = idLiga;
    }
    public String getDescripcionLiga() {
        return this.descripcionLiga;
    }
    
    public void setDescripcionLiga(String descripcionLiga) {
        this.descripcionLiga = descripcionLiga;
    }
    public Set<Equipo> getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set<Equipo> equipos) {
        this.equipos = equipos;
    }




}


