package modelo.dto;
// Generated 04-sep-2018 14:31:52 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Partido generated by hbm2java
 */
public class Partido  implements java.io.Serializable {


     private Integer idPartido;
     private Equipo equipoByEquipo2;
     private Equipo equipoByEquipo1;
     private int idLiga;
     private String equipoGanador;
     private String equipoPerdedor;
     private Date fechaPartido;

    public Partido() {
    }

	
    public Partido(Equipo equipoByEquipo2, Equipo equipoByEquipo1, int idLiga, Date fechaPartido) {
        this.equipoByEquipo2 = equipoByEquipo2;
        this.equipoByEquipo1 = equipoByEquipo1;
        this.idLiga = idLiga;
        this.fechaPartido = fechaPartido;
    }
    public Partido(Equipo equipoByEquipo2, Equipo equipoByEquipo1, int idLiga, String equipoGanador, String equipoPerdedor, Date fechaPartido) {
       this.equipoByEquipo2 = equipoByEquipo2;
       this.equipoByEquipo1 = equipoByEquipo1;
       this.idLiga = idLiga;
       this.equipoGanador = equipoGanador;
       this.equipoPerdedor = equipoPerdedor;
       this.fechaPartido = fechaPartido;
    }
   
    public Integer getIdPartido() {
        return this.idPartido;
    }
    
    public void setIdPartido(Integer idPartido) {
        this.idPartido = idPartido;
    }
    public Equipo getEquipoByEquipo2() {
        return this.equipoByEquipo2;
    }
    
    public void setEquipoByEquipo2(Equipo equipoByEquipo2) {
        this.equipoByEquipo2 = equipoByEquipo2;
    }
    public Equipo getEquipoByEquipo1() {
        return this.equipoByEquipo1;
    }
    
    public void setEquipoByEquipo1(Equipo equipoByEquipo1) {
        this.equipoByEquipo1 = equipoByEquipo1;
    }
    public int getIdLiga() {
        return this.idLiga;
    }
    
    public void setIdLiga(int idLiga) {
        this.idLiga = idLiga;
    }
    public String getEquipoGanador() {
        return this.equipoGanador;
    }
    
    public void setEquipoGanador(String equipoGanador) {
        this.equipoGanador = equipoGanador;
    }
    public String getEquipoPerdedor() {
        return this.equipoPerdedor;
    }
    
    public void setEquipoPerdedor(String equipoPerdedor) {
        this.equipoPerdedor = equipoPerdedor;
    }
    public Date getFechaPartido() {
        return this.fechaPartido;
    }
    
    public void setFechaPartido(Date fechaPartido) {
        this.fechaPartido = fechaPartido;
    }




}


