package modelo.dto;
// Generated 04-sep-2018 14:31:52 by Hibernate Tools 4.3.1



/**
 * Premio generated by hbm2java
 */
public class Premio  implements java.io.Serializable {


     private Integer idPremio;
     private Equipo equipo;
     private String descripcionPremio;

    public Premio() {
    }

    public Premio(Equipo equipo, String descripcionPremio) {
       this.equipo = equipo;
       this.descripcionPremio = descripcionPremio;
    }
   
    public Integer getIdPremio() {
        return this.idPremio;
    }
    
    public void setIdPremio(Integer idPremio) {
        this.idPremio = idPremio;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public String getDescripcionPremio() {
        return this.descripcionPremio;
    }
    
    public void setDescripcionPremio(String descripcionPremio) {
        this.descripcionPremio = descripcionPremio;
    }




}


