package modelo.dto;
// Generated 04-sep-2018 14:31:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Titular generated by hbm2java
 */
public class Titular  implements java.io.Serializable {


     private Integer idTitular;
     private String descripcionTitular;
     private Set<Jugador> jugadors = new HashSet<Jugador>(0);

    public Titular() {
    }

	
    public Titular(String descripcionTitular) {
        this.descripcionTitular = descripcionTitular;
    }
    public Titular(String descripcionTitular, Set<Jugador> jugadors) {
       this.descripcionTitular = descripcionTitular;
       this.jugadors = jugadors;
    }
   
    public Integer getIdTitular() {
        return this.idTitular;
    }
    
    public void setIdTitular(Integer idTitular) {
        this.idTitular = idTitular;
    }
    public String getDescripcionTitular() {
        return this.descripcionTitular;
    }
    
    public void setDescripcionTitular(String descripcionTitular) {
        this.descripcionTitular = descripcionTitular;
    }
    public Set<Jugador> getJugadors() {
        return this.jugadors;
    }
    
    public void setJugadors(Set<Jugador> jugadors) {
        this.jugadors = jugadors;
    }




}


